### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by reignmaker** [ceolter/ag-grid-enterprise-mysql-example#1]
Hello. Your sample is not working. It does not send any params to the server.
And it throws an error:
```
TypeError: Cannot read property 'length' of undefined
    at OlympicWinnersDao.isDoingGrouping (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/src/server/olympicWinnersDao.js:133:24)
    at OlympicWinnersDao.createSelectSql (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/src/server/olympicWinnersDao.js:8:14)
    at OlympicWinnersDao.list (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/src/server/olympicWinnersDao.js:185:26)
    at /home/ubuntu/workspace/ag-grid-enterprise-mysql-example/start.js:11:23
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/workspace/ag-grid-enterprise-mysql-example/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ubuntu/workspace/ag-grid-enterprise-mysql-example/node_modules/express/lib/router/index.js:335:12)
```

**Comment by ceolter** [comment]
looking now. i think it needs it's versions cleaned up. sorry about this.

**Comment by ceolter** [comment]
fixed. the version of the dependencies was wrong. should of been on v10 of ag-grid.

i've also updated version of this example to v10 and done a release.

**Comment by reignmaker** [comment]
Awesome! Thank you!
